### ISSUE TITLE
Support Alternative MinReplicaCount for HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by techdecline** [rekuberate-io/sleepcycles#17]
Hi, 

when evaluating the project, we were wondering if the MinReplicaCount for HorizontalPodAutoscalers could be modified from its default of 1 in case of shutdown?

Thanks,
Cornelius

**Comment by akyriako** [comment]
Hi @techdecline, apologies for the late reply and thank you for taking an interest on evaluating sleepcycles.

I assume (please describe your use case if it is otherwise) that you are interested setting the HPA **minReplicas to 0**. The answer is that is **not** supported. Actually not allowing zero minReplicas is **by design**, and let me explain you why: In order to be able to set minReplicas to zero you need to enable the `HPAScaleToZero` feature gate in your kubernetes cluster, otherwise setting minReplicas to 0, although is technically allowed, will throw an error. Aiming to have a uniform behavior of rekuberate-io/sleepcycles regardless if it's running on local, bare-metal or managed kubernetes clusters (where usually cloud providers tend **not** to enable unstable or beta features such as `HPAScaleToZero`) this option was left out, because it would require additional tweaking during the cluster installation and might introduce confusing errors to managed kubernetes clusters users, that could be perceived as malfunction of sleepcycles. 

You can find a very thorough analysis of HPA and this feature gate in this blog post: https://midbai.com/en/post/hpa-scale-to-zero/

Best regards,
Kyriakos

**Comment by techdecline** [comment]
Hi @akyriako,

many thanks for coming back to this issue. We were actually looking for a way to scale down in low-load scenarios to 2-3 replicas using this project and HPA. As we are still struggling with reasonably well working readiness probes, this would allow for some automation without loosing HA on Pod level during the nights.

Is this possibly without the need of two independent sleepcycle definitions?

Many thanks and best regards,
Cornelius

**Comment by akyriako** [comment]
Hi @techdecline, I think allowing ad-hoc minReplicas is not something I want to add to the tool right now (it will cancel the whole put-to-sleep-easy idea and it will divert into the scaling field that other tools really shine taking into consideration multiple other parameters which of course increase the complexity of those tools and the overhead of administering them in your cluster). I would suggest you have a look at KEDA Cron Scalers [https://keda.sh/docs/2.0/scalers/cron/](https://keda.sh/docs/2.0/scalers/cron/) which are doing a bit the inverse thing but can lead to the same result. Nevertheless, they come with a big baggage that you have to take care of, which is called KEDA and ScaledObjects. It is a trade-off as everything else in our field of work.

Best regards,
Kyriakos

**Comment by techdecline** [comment]
Hey @akyriako,

I totally get your point as adding functionality is always adding complexity in the form of parameters, documentation etc. We are actively  pursuing KEDA right now, but I wanted to follow up on this as complexity-wise, your solution seemed very solid and clean. 

Thanks again for getting back, I think we can close the issue for now!
