### ISSUE TITLE
Sleepcycle ignores wakeup schedule

### ISSUE THREAD

**Issue by arnikasky** [rekuberate-io/sleepcycles#9]
Hello @akyriako 

First of all, thank you for this tool, it helps us to decrease costs.
But I implemented it in different namespaces, and time to time wakeup schedule is ignored, and last action is Watch.
For example, logs from one env:

```
NAME                 SHUTDOWN SCHEDULE   SHUTDOWN TIMEZONE   WAKEUP SCHEDULE   WAKEUP TIMEZONE   ENABLED   SUCCESS   LAST OP
sleepcycle   0 23 * * 1-5        Europe/Warsaw       0 7 * * 1-5       Europe/Warsaw     true      true      Watch
```

Could you please help me? Maybe, you can help how I can debug this problem.

Best regards, 
Hanna

**Comment by akyriako** [comment]
Hi Hanna,

First of all thanks for adopting sleepcycles! I had a quick look on that today, because it sounds weird. 

Here is the setup I used:
**namespace**: app-1, **deployments**: 2 traefik/whoami workloads app-1-1, app-1-2, **sleepcycle**: sleepcycle-app-1
**namespace**: app-2, **deployments**: 1 traefik/whoami workload app-2, **sleepcycle**: sleepcycle-app-2

You can see it live working in the short screencast below:

[Screencast from 05-24-2024 11:13:28 AM.webm](https://github.com/rekuberate-io/sleepcycles/assets/3920167/275f5780-6bc7-4904-a4bb-71a440729a39)

In the meantime, I would propose as a first debugging step to inspect the metadata of the sleepcycle, and check whether the next scheduled operations timestamps are matching your cron expression expectations, e.g:

![Screenshot from 2024-05-24 11-41-18](https://github.com/rekuberate-io/sleepcycles/assets/3920167/0088da2c-2daa-4619-9db9-2b8d9ca9ca98)

If the next and previous operation are not within or near the boundaries a certain time-window of you cron expression, approximately +-15secs (as in your case they lay in the future) the controller will evaluate your workloads connected with that sleepcycle, but because it took no action, it will declare **Watch** as the last successful operation (which is actually true and correct).

Nevertheless, I wonder if this is a corner case that went under the radar and it is somehow behaving erratic. Could you please give me a little more context of your set up in order to recreate the issue as it occurs in your environment? 

Best regards,
Kyriakos

**Comment by akyriako** [comment]
I would strongly suggest, if all your debugging actions are fruitless, to reinstall sleepcycles, as I updated the container image and the latest is:
> akyriako78/rekuberate-io-sleepcycles:**0.2.0** 

Make sure, you **make a copy of your sleepcycles CR manifests before uninstalling**, because `helm uninstall` will wipe those out as well. 

PS: If you are installing via the`helm install rekuberate-io-sleepcycles config/helm/` command, as mentioned in README, you don't need to change anything yourself, helm will bring the new container image mentioned above.

**Comment by arnikasky** [comment]
Hello @akyriako!
Sorry for the late answer, I just found easy fix for my problem.
As I said we have multiple namespaces and sleepcycle in each namespace.
I just changed cron expression and set up different time for all sleepcycles and now wakeup action works well.
Now I see the same problem with shutdown action and will implement the same fix.
Thank you for your investigation, I'll probably reinstall helm chart too.

**Comment by akyriako** [comment]
Hallo @arnikasky, 

I am glad you found a workaround but I would like to let you know I have released a new version after you reported the issue, which I analyzed and was indeed a corner case that could occur. I am not a fan of workarounds in general and I would like to provide staff that are working reliable under any circumstances so please take the chance and check the README.md to see the overall changes in sleepcycles, that now guarantee that this will not happen again no matter what.

(If you want more info about the corner case and under which circumstances it occurs I am willing to transparently elaborate)  

Please do not hesitate to give feedback or to come up with any question.

I do have a question from my side though. Would the organization you're working would be interested in one of the following?

- List their name in a table of sleepcycles adopters ? AND/OR
- Would they be interested in co-writing a white paper of how you/they are using sleepcycles and the benefits out of that? 

Thanks again for adopting sleepcycles and more over for finding out this malfunctioning corner case!
